# Generated by Django 4.2.7 on 2023-11-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("highlights", "0005_remove_highlight_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
            ],
        ),
    ]
